types:
  JSONObject: map[string]interface{}

objects:
  Scheduler:
    ID: string
    Schedule: string
    JobName: string
    Input: JSONObject
    CreatedAt: string
    UpdatedAt: string
  ListSchedulersRequest:
    PageToken: string
    PageSize: int
  ListSchedulersResponse:
    Schedulers: "[]*Scheduler"
    NextPageToken: string

routes:
  /schedulers:
    GET:
      name: ListSchedulers
      query_params: "*ListSchedulersRequest"
      response_body: "*ListSchedulersResponse"
    POST:
      name: PostScheduler
      request_body: "*Scheduler"
      response_body: "*Scheduler"
  /schedulers/{schedulerID}:
    GET:
      name: GetScheduler
      response_body: "*Scheduler"
    PUT:
      name: PutScheduler
      request_body: "*Scheduler"
      response_body: "*Scheduler"
    DELETE:
      name: DeleteScheduler
