objects:
  Config:
    Name: string
    ClientID: string
    ClientSecret: string
    AuthURL: string
    TokenURL: string
    RedirectURL: string
    Scopes: "[]string"
    AuthURLParams: "map[string]string"
    CreatedAt: string
    UpdatedAt: string
  Token:
    AccessToken: string
    TokenType: string
    RefreshToken: string
    Expiry: string
  Provider:
    Name: string
    Config: "*Config"
  GetOAuthTokenRequest:
    Code: string
  GetOAuthAuthorizationURLResponse:
    URL: string
  ListOAuthProvidersRequest:
    PageToken: string
    PageSize: int
  ListOAuthProvidersResponse:
    Providers: "[]*Provider"
    NextPageToken: string

routes:
  /oauth/providers:
    GET:
      name: ListProviders
      query_params: "*ListOAuthProvidersRequest"
      response_body: "*ListOAuthProvidersResponse"
  /oauth/providers/{name}/authorize:
    GET:
      name: GetOAuthAuthorizationURL
      response_body: "*GetOAuthAuthorizationURLResponse"
  /oauth/providers/{name}/token:
    POST:
      name: GetOAuthToken
      request_body: "*GetOAuthTokenRequest"
      response_body: "*Token"
  /oauth/providers/{name}/config:
    GET:
      name: GetOAuthConfig
      response_body: "*Config"
    PUT:
      name: PutOAuthConfig
      request_body: "*Config"
      response_body: "*Config"
    DELETE:
      name: DeleteOAuthConfig
