types:
  JSONObject: map[string]interface{}

objects:
  Job:
    ID: string
    Name: string
    Status: string
    Input: JSONObject
    ScheduledFor: "*string"
    SucceededAt: "*string "
    ErroredAt: "*string"
    ClaimedAt: "*string"
    CreatedAt: string
    UpdatedAt: string
  ListJobsQueryParams:
    PageSize: int
    PageToken: string
  ListJobsResponse:
    Jobs: "[]*Job"
    NextPageToken: "string"
  ClaimSomeJobRequest:
    Names: "[]string"

routes:
  /jobs:
    GET:
      name: ListJobs
      query_params: "*ListJobsQueryParams"
      response_body: "*ListJobsResponse"
  /jobs/{jobID}:
    GET:
      name: GetJob
      response_body: "*Job"
    DELETE:
      name: DeleteJob
  /jobs:queue:
    POST:
      name: QueueJob
      request_body: "*Job"
      response_body: "*Job"
  /jobs:claim:
    POST:
      name: ClaimSomeJob
      request_body: "*ClaimSomeJobRequest"
      response_body: "*Job"
  /jobs/{jobID}:claim:
    POST:
      name: ClaimJob
      response_body: "*Job"
  /jobs/{jobID}:release:
    POST:
      name: ReleaseJob
      response_body: "*Job"
  /jobs/{jobID}:success:
    POST:
      name: SetJobSuccess
      response_body: "*Job"
  /jobs/{jobID}:error:
    POST:
      name: SetJobError
      response_body: "*Job"
