name: Go Lint

on: [push, pull_request]

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  
      - name: Run `golangci-lint`
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39.0
          working-directory: server
